parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Factory\ProjectGroupFactoryInterface: '@App\Factory\ProjectGroupFactory'
    App\Factory\ProjectFactoryInterface: '@App\Factory\ProjectFactory'

    App\EventListener\CreateProjectGroupsListener:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $projectGroupFactory: '@App\Factory\ProjectGroupFactoryInterface'
        tags:
            - { name: kernel.event_listener, event: App\Event\ProjectCreatedEvent, method: "onProjectCreate" }