parameters:
    student_pagination_limit: 5

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Factory\ProjectGroupFactoryInterface: '@App\Factory\ProjectGroupFactory'
    App\Factory\ProjectFactoryInterface: '@App\Factory\ProjectFactory'

    App\EventListener\CreateProjectGroupsListener:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $projectGroupFactory: '@App\Factory\ProjectGroupFactoryInterface'
        tags:
            - { name: kernel.event_listener, event: App\Event\ProjectCreatedEvent, method: "onProjectCreate" }

    App\Service\StudentServiceInterface:
        class: 'App\Service\StudentService'
        arguments:
             $studentPaginationLimit: '%student_pagination_limit%'

    App\Validator\UniqueNameValidator:
        arguments:
            $studentRepository: '@App\Repository\StudentRepository'
        tags: [ 'validator.constraint_validator' ]

    App\EventListener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }